/**
 * @type {import('@remix-run/dev').AppConfig}
 */
module.exports = {
  cacheDirectory: "./node_modules/.cache/remix",
  ignoredRouteFiles: ["**/.*", "**/*.css", "**/*.test.{js,jsx,ts,tsx}"],
  future: {
    unstable_tailwind: true,
    v2_routeConvention: true,
    v2_normalizeFormMethod: true,
    v2_meta: true,
    v2_errorBoundary: true,
  },
  // the whole rehype universe is there to support syntax highlighting
  // and it's all ESM so we need to bundle it... 🥲
  serverDependenciesToBundle: [
    /^bail.*/,
    /^ccount.*/,
    /^character-entities.*/,
    /^character-entities-html4.*/,
    /^character-entities-legacy.*/,
    /^character-reference-invalid.*/,
    /^comma-separated-tokens.*/,
    /^decode-named-character-reference.*/,
    /^hastscript.*/,
    /^hast-util-from-parse5.*/,
    /^hast-util-parse-selector.*/,
    /^hast-util-to-string.*/,
    /^hast-util-to-html.*/,
    /^hast-util-whitespace.*/,
    /^html-void-elements.*/,
    /^is-decimal.*/,
    /^is-hexadecimal.*/,
    /^is-alphanumerical.*/,
    /^is-alphabetical.*/,
    /^is-plain-obj.*/,
    /^parse-entities.*/,
    /^property-information.*/,
    /^refractor.*/,
    /^rehype.*/,
    /^rehype-prism-plus.*/,
    /^rehype-parse.*/,
    /^rehype-stringify.*/,
    /^space-separated-tokens.*/,
    /^stringify-entities.*/,
    /^trough.*/,
    /^unified.*/,
    /^unist-util-is.*/,
    /^unist-util-filter.*/,
    /^unist-util-stringify-position.*/,
    /^unist-util-visit.*/,
    /^unist-util-visit-parents.*/,
    /^vfile.*/,
    /^vfile-location.*/,
    /^vfile-message.*/,
    /^web-namespaces.*/,
    /^zwitch.*/,
  ],
};
